dist: trusty
language: python
sudo: true
services:
  - rabbitmq

python:
  - "3.5"
  - "3.6"

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
  - pip install codecov

script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"
  - tox

after_success:
  - codecov

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false
