dist: xenial

language: python

sudo: false

addons:
  apt:
    packages:
      - rabbitmq-server

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - PYTHONASYNCIODEBUG=1

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
  - pip install codecov

script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"
  - tox

after_success:
  - codecov

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false

deploy:
  provider: pypi
  user: hellysmile
  password:
    secure: KdES3kx9wD7ZSOb/Gv91X8P/kqn6K0NK1EIJg6ekkA3aZBVDC/oOqdaY6GbFZIyjrmTRfCsFvQKFJOyxi5LhuPa7KCrAkeGZFWtVtbKN0WIvdFYtNb2NR4vHENpiQgPZ9x9URQavTJCyOMTRDb5AA8u1KQarpA1jSt80kdaSQupGumZmBCNdLiwD4Mz/UXbtMsRf4vNieOOZTdZj8TEg7xIjVI6b4/afyk/n8jT/tWjjj2vfMBGxqkdkzaSIbyYPqOWh6VvHnUr5E9Vap14GIoCk2UpcxD1/vjVGDAFBXLNDjbTOss5KBa9OoWgj2tcWjoK0wA4NGGGepf7HdoOgZTs6qccUZUVIDLu2BiMc6DVY4r3xRNZhGe259ywRqOk4lwZqvEdkK9r3ZOmqqfeHZYmxKo9TN1L44i8rKC0dsM786JxiEuNkUtz6T7t2fVvbhRqdyMtE8TqaDdpLsn7XPYXJ3I1MLq9JdxORWUA1ubLIY7HmHSKXdh+PLYFXmQwF7ZUmHEloLyipJf1TW2vklehrbAUbD0lgjunu3YFmkUDjjbuW2BIWUztWNjMWHc24+qsPI6uc8vvpi9q3OXo+nPW6ahBQhd/kRciDSBrOqKoXpK1Z8NzkeI5pl/Y0y8t00u9wd0T2GU0dpNpAEzyG2STTyaknG2aaoMZT5J/RF00=
  on:
    tags: true
    all_branches: true
    python: 2.7
